### ISSUE TITLE
"string indices must be integers" when handling an error

### ISSUE THREAD

**Issue by codl** [halcy/Mastodon.py#160]
```
TypeError('string indices must be integers',)

Traceback (most recent call last):
...
  File "/home/codl/forget/libforget/mastodon.py", line 165, in refresh_posts
    status = api.status(post.mastodon_id)
  File "</home/codl/.local/share/virtualenvs/forget-jXTy0Bc2/lib/python3.6/site-packages/decorator.py:decorator-gen-10>", line 2, in status
  File "/home/codl/.local/share/virtualenvs/forget-jXTy0Bc2/lib/python3.6/site-packages/mastodon/Mastodon.py", line 77, in wrapper
    return function(self, *args, **kwargs)
  File "/home/codl/.local/share/virtualenvs/forget-jXTy0Bc2/lib/python3.6/site-packages/mastodon/Mastodon.py", line 620, in status
    return self.__api_request('GET', url)
  File "/home/codl/.local/share/virtualenvs/forget-jXTy0Bc2/lib/python3.6/site-packages/mastodon/Mastodon.py", line 2202, in __api_request
    error_msg = response['error']
```

this is the code in question ↓

https://github.com/halcy/Mastodon.py/blob/55ec333562d49ac8ac65000e0c01ae88255576f1/mastodon/Mastodon.py#L2197-L2204

i think i wrote this, haha

my best guess for how this could happen is if the error page returns a bare json string with the word "error" in it. i think this was on a pleroma instance but i couldnt look into it further at the time

**Comment by codl** [comment]
wait lol it's just missing an else isn't it

```patch
@@ -2200,2202 +2200,2203 @@
          if not isinstance(response, dict) or 'error' not in response:
              error_msg = None
-         error_msg = response['error']
+         else:
+             error_msg = response['error']
```

I'm going to make sure I can reproduce it though before I send a PR

**Comment by jfmcbrayer** [comment]
Pleroma does send bare json strings with the word "error" (I've seen this error several times in brutaldon on a Pleroma instance).
