### ISSUE TITLE
Call to domain_blocks is broken, because returning "rel"="pref" does not work

### ISSUE THREAD

**Issue by arittner** [halcy/Mastodon.py#232]
I've a blocked domain in my account and a call to 

~~~python
mastodon.domain_blocks()
~~~

runs in an error:

~~~
Traceback (most recent call last):
  File "C:\Users\aritt\AppData\Roaming\JetBrains\IdeaIC2021.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\aritt\AppData\Roaming\JetBrains\IdeaIC2021.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/DevTools/Core/gitrepo/mastodon-playground/mb-block.py", line 54, in <module>
    dump_blocks(mastodon.domain_blocks())
  File "C:\DevTools\Core\Python39\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\DevTools\Core\Python39\lib\site-packages\mastodon\Mastodon.py", line 102, in wrapper
    return function(self, *args, **kwargs)
  File "C:\DevTools\Core\Python39\lib\site-packages\mastodon\Mastodon.py", line 1542, in domain_blocks
    return self.__api_request('GET', '/api/v1/domain_blocks', params)
  File "C:\DevTools\Core\Python39\lib\site-packages\mastodon\Mastodon.py", line 3489, in __api_request
    response[0]._pagination_prev = prev_params
AttributeError: 'str' object has no attribute '_pagination_prev'
python-BaseException
~~~

parse_header_links resolves the response with this value:

~~~
[{'url': 'https://social.tchncs.de/api/v1/domain_blocks?since_id=2922', 'rel': 'prev'}]
~~~

The "rel: prev " handling try to manage the pagination, but the response does not contain a pagination object (it's a plain JSON List of Strings):

~~~json
["truthsocial.co.in"]
~~~

So, the call of:

~~~python
response[0]._pagination_prev = prev_params
~~~

... raise `AttributeError: 'str' object has no attribute '_pagination_prev'`

**Comment by arittner** [comment]
Info about the instance: https://social.tchncs.de/about/more (v3.5.3)

**Comment by arittner** [comment]
Ananlysis:

API call responses with a plain JSON List like:

~~~json
["domain.de", "example.com", "blabla.social"]
~~~

The json parser create a pure List:

~~~python
            if parse == True:
                try:
                    response = response_object.json(object_hook=self.__json_hooks)
~~~

`response List: ["domain.de", "example.com", "blabla.social"]`

and not a Dict. But in:

~~~
File "C:\DevTools\Core\Python39\lib\site-packages\mastodon\Mastodon.py", line 3489, in __api_request
~~~

the code tries to access a dict and put a key/value:

~~~python
response[0]._pagination_prev = prev_params
~~~

This means the special case of a list response should be handled. Maybe a creation of a Dict and embed the plain list.

**Comment by arittner** [comment]
Hello @halcy 

The main reason, because it fails is the handling in json.decode. The object_hook=self.__json_hooks will never be used for non-json objects and strings in a list are not json objects. This means, we'll never get a wrapped AttribAccessDict.

The following test will show it:

~~~python
from json import JSONDecoder


class AttribAccessDict(dict):
    def __getattr__(self, attr):
        if attr in self:
            return self[attr]
        else:
            raise AttributeError("Attribute not found: " + str(attr))

    def __setattr__(self, attr, val):
        if attr in self:
            raise AttributeError("Attribute-style access is read only")
        super(AttribAccessDict, self).__setattr__(attr, val)


def __json_allow_dict_attrs(json_object):
    """
    Makes it possible to use attribute notation to access a dicts
    elements, while still allowing the dict to act as a dict.
    """
    if isinstance(json_object, dict):
        return AttribAccessDict(json_object)
    return json_object


def __json__hooks(json_object):
    json_object = __json_allow_dict_attrs(json_object)
    return json_object


json_t1 = '[{"test1": true}, {"test2": false}]'
json_t2 = '["test1", "test2"]'

dec: JSONDecoder = JSONDecoder(object_hook=__json__hooks)

t1 = dec.decode(json_t1)
t2 = dec.decode(json_t2)

assert isinstance(t1[0], AttribAccessDict)
assert isinstance(t1[1], AttribAccessDict)

assert isinstance(t2[0], str)
assert isinstance(t2[1], str)
~~~

With a breakpoint on `__json__hooks` it's obvious, for test case 2 the function hook was never called.


@halcy, but my question now is: Why we need `AttribAccessDict` for any JSON Object in a list? AttribAccessDict  is only used to add the protected attributes `_pagination_prev` and `_pagination_next` to the first and last element in the list. 

I guess this can be simplified. Define only a class `AttribAccessList` and wrap it around the response list. And then put the protected attributes `_pagination_prev` and `_pagination_next` to the `AttribAccessList instead of the list elements.

So, the new class looks very similar to `AttribAccessDict`:

~~~python
class AttribAccessList(list):
    def __getattr__(self, attr):
        if attr in self:
            return self[attr]
        else:
            raise AttributeError("Attribute not found: " + str(attr))

    def __setattr__(self, attr, val):
        if attr in self:
            raise AttributeError("Attribute-style access is read only")
        super(AttribAccessList, self).__setattr__(attr, val)
~~~

And now, we can wrap it in the `__api_request` function:

~~~python 
...
            # Parse link headers
            if isinstance(response, list) and \
                    'Link' in response_object.headers and \
                    response_object.headers['Link'] != "":
                response = AttribAccessList(response)
                tmp_urls = requests.utils.parse_header_links(
                    response_object.headers['Link'].rstrip('>').replace('>,<', ',<'))
...
~~~

and later we can set the protected attributes:

~~~python
...
                            if "since_id" in next_params:
                                del next_params['since_id']
                            if "min_id" in next_params:
                                del next_params['min_id']
                            response._pagination_next = next_params
...
                            if since_id.isdigit():
                                prev_params['since_id'] = int(since_id)
                            else:
                                prev_params['since_id'] = since_id
                            if "max_id" in prev_params:
                                del prev_params['max_id']
                            response._pagination_prev = prev_params
...
~~~

Now we can also change `fetch_previous` and `fetch_next` accordingly (this means, remove the index access `[0]` and `[-1]`)

Finally, the class `AttribAccessDict` can be removed and also the function to wrap it in the function hook.

What do you think, Lorenz? Is that sufficient as a solution? Or am I missing something?
