### ISSUE TITLE
Broken streaming connection

### ISSUE THREAD

**Issue by melocery** [halcy/Mastodon.py#243]
Hi,
I use the Matodon.py as a part of my auto-reply bot. 
When I connect to streaming api, everything goes well but with extended period time of usage, weird error appears: 

```
Traceback (most recent call last):
  File "/root/miniconda3/envs/mastbot/lib/python3.8/site-packages/urllib3/response.py", line 700, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/mastbot/lib/python3.8/site-packages/urllib3/response.py", line 441, in _error_catcher
    yield
  File "/root/miniconda3/envs/mastbot/lib/python3.8/site-packages/urllib3/response.py", line 767, in read_chunked
    self._update_chunk_length()
  File "/root/miniconda3/envs/mastbot/lib/python3.8/site-packages/urllib3/response.py", line 704, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/mastbot/lib/python3.8/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/root/miniconda3/envs/mastbot/lib/python3.8/site-packages/urllib3/response.py", line 575, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/root/miniconda3/envs/mastbot/lib/python3.8/site-packages/urllib3/response.py", line 796, in read_chunked
    self._original_response.close()
  File "/root/miniconda3/envs/mastbot/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/miniconda3/envs/mastbot/lib/python3.8/site-packages/urllib3/response.py", line 458, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/mastbot/lib/python3.8/site-packages/mastodon/streaming.py", line 64, in handle_stream
    for chunk in response.iter_content(chunk_size = 1):
  File "/root/miniconda3/envs/mastbot/lib/python3.8/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dogchan.py", line 102, in <module>
    mastodon.stream_user(rl) #go!
  File "/root/miniconda3/envs/mastbot/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/miniconda3/envs/mastbot/lib/python3.8/site-packages/mastodon/Mastodon.py", line 102, in wrapper
    return function(self, *args, **kwargs)
  File "/root/miniconda3/envs/mastbot/lib/python3.8/site-packages/mastodon/Mastodon.py", line 3110, in stream_user
    return self.__stream('/api/v1/streaming/user', listener, run_async=run_async, timeout=timeout, reconnect_async=reconnect_async, reconnect_async_wait_sec=reconnect_async_wait_sec)
  File "/root/miniconda3/envs/mastbot/lib/python3.8/site-packages/mastodon/Mastodon.py", line 3628, in __stream
    listener.handle_stream(r)
  File "/root/miniconda3/envs/mastbot/lib/python3.8/site-packages/mastodon/streaming.py", line 89, in handle_stream
    six.raise_from(
  File "<string>", line 3, in raise_from
mastodon.Mastodon.MastodonNetworkError: Server ceased communication.
```

I changed the instance of my bot, this error disappeared. So I assume there is someting wrong with my instance configuration. But I have no idea to fix it. Do you have any advice? Any advice would be appreciated.

**Comment by arittner** [comment]
Hello @melocery!

This actually looks like a server-side interruption, to which `Mastodon.py` can only respond with errors. Unfortunately, I can't say what causes this. But I don't know the setup of the server. Probably there are some timeouts in play, which cut the connection hard at some point. But this is all speculation.

However, you maybe can handle this on your client side. On catching the `MastodonNetworkError` you can reestablish the streaming (in a loop). It may happen, however, that a few messages sent meanwhile are lost.

**Comment by melocery** [comment]
@arittner  Thank you for your reply!!! I'll try the loop.

**Comment by halcy** [comment]
Did it work for you?

You can also pass "reconnect_async" to have mastodon.py take care of that. Given that you didn't find that option, I should probably point that out more strongly.
