### ISSUE TITLE
Report functionality is broken

### ISSUE THREAD

**Issue by drequivalent** [halcy/Mastodon.py#244]
Trying to report a spammer. When `status_ids` is set:
```
Traceback (most recent call last):
  File "/root/mastodon-bot-autoresponder/autoresponder.py", line 215, in <module>
    main()
  File "/root/mastodon-bot-autoresponder/autoresponder.py", line 212, in main
    run_bot(config)
  File "/root/mastodon-bot-autoresponder/autoresponder.py", line 154, in run_bot
    api.report(msgaccount, status_ids = notification['status']['id'], comment="Spamming the same message into a public message group, please ban ASAP", forward=True)
  File "</usr/local/lib/python3.7/dist-packages/decorator.py:decorator-gen-88>", line 2, in report
  File "/usr/local/lib/python3.7/dist-packages/mastodon/Mastodon.py", line 100, in wrapper
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mastodon/Mastodon.py", line 2155, in report
    return self.__api_request('POST', '/api/v1/reports/', params)
  File "/usr/local/lib/python3.7/dist-packages/mastodon/Mastodon.py", line 3049, in __api_request
    error_msg)
mastodon.Mastodon.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 'Record not found')
```

When `status_ids` is not set:

```
Traceback (most recent call last):
  File "/root/mastodon-bot-autoresponder/autoresponder.py", line 215, in <module>
    main()
  File "/root/mastodon-bot-autoresponder/autoresponder.py", line 212, in main
    run_bot(config)
  File "/root/mastodon-bot-autoresponder/autoresponder.py", line 154, in run_bot
    api.report(msgaccount, status_ids = None, comment="Spamming the same message into a public message group, please ban ASAP", forward=True)
  File "</usr/local/lib/python3.7/dist-packages/decorator.py:decorator-gen-88>", line 2, in report
  File "/usr/local/lib/python3.7/dist-packages/mastodon/Mastodon.py", line 100, in wrapper
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mastodon/Mastodon.py", line 2148, in report
    status_ids = list(map(lambda x: self.__unpack_id(x), status_ids))
TypeError: 'NoneType' object is not iterable
```
Can't send a report either way.

**Comment by arittner** [comment]
Thank you for your report. I'll check it.

**Comment by arittner** [comment]
Hi @drequivalent!

The second issue is clear for me. This can be easily fixed. The first issue with the 404 is interesting. Record not found, means the API endpoint is existing, but one of the IDs is not correct. But no information, what is incorrect. Maybe the status ID, might be the account ID. 

The status could have already been deleted? Or the status ID, or the account ID, was really not correct?

**Comment by arittner** [comment]
Hello @drequivalent 

I resolved the issue with `status_ids = None`. The 404 error is currently unclear to me. Maybe you can check a report with the account_id only (and let status_ids = None). If you still get a 404, it's the account ID you want to report. Do you use the internal number for the account ID? It's not the account-name (like @a@example.social), it should be a positive integer. 

You are welcome to reopen the issue, if you see Mastodon.py as the bad player ;-)
