### ISSUE TITLE
Pagination for context?

### ISSUE THREAD

**Issue by edent** [halcy/Mastodon.py#259]
Is it possible to use `fetch_remaining` with a `context`?

I want to capture a conversation thread.

This works:

```python
root_id = 109335596782650130
root = mastodon.status(root_id)
replies = mastodon.status_context(root_id)
```

It fetches the first 20 replies.

This fails:
```
all_replies = mastodon.fetch_remaining(replies)
```

With:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/edent/.local/lib/python3.10/site-packages/mastodon/Mastodon.py", line 3162, in fetch_remaining
    current_page = self.fetch_next(current_page)
  File "/home/edent/.local/lib/python3.10/site-packages/mastodon/Mastodon.py", line 3115, in fetch_next
    method = params['_pagination_method']
KeyError: '_pagination_method'
```

The documentation - https://docs.joinmastodon.org/entities/context/ - doesn't say whether it is paginated or not. But on the web it appears to be.

I can do pagination on other objects. Am I missing something obvious?

**Comment by edent** [comment]
Ignore me. I'm being stupid. The call gets *all* the replies.
