### ISSUE TITLE
mastodon.timeline broken due to `datetime` not being a type.

### ISSUE THREAD

**Issue by kentarospin98** [halcy/Mastodon.py#262]
```py
mastodon.timeline(timeline="home", since_id="00000")
```

causes

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kensp/Documents/fern/env/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/kensp/Documents/fern/env/lib/python3.10/site-packages/mastodon/Mastodon.py", line 111, in wrapper
    return function(self, *args, **kwargs)
  File "/home/kensp/Documents/fern/env/lib/python3.10/site-packages/mastodon/Mastodon.py", line 819, in timeline
    since_id = self.__unpack_id(since_id, dateconv=True)
  File "/home/kensp/Documents/fern/env/lib/python3.10/site-packages/mastodon/Mastodon.py", line 3928, in __unpack_id
    if dateconv and isinstance(id, datetime):
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
```

**Comment by kentarospin98** [comment]
https://github.com/halcy/Mastodon.py/blob/725f79466de65743df0c3498a1bb08e106b5209e/mastodon/Mastodon.py#L3926

Never mind it's been fixed.

**Comment by halcy** [comment]
Too lazy to tag it, but I just pushed that fix and others besides to pypi (and more tests, to make sure that that part of the code works. I do wish I had better coverage)
