### ISSUE TITLE
Stream doesn't reconnect on certain exceptions

### ISSUE THREAD

**Issue by ianh** [halcy/Mastodon.py#323]
Hi -- I've been noticing a problem where sometimes the object passed to `stream_user` will stop getting notifications.  I attached a syslog including the traceback of where it seems to occur.  What appears to be happening is: since the exception is a `requests.exceptions.ConnectionError`, and not an `AttributeError`, `MastodonMalformedEventError`, `MastodonNetworkError`, `ChunkedEncodingError`, or `MastodonReadTimeout`, it falls through the `catch` statements which are designed to apply the reconnect logic. 

[syslog.txt](https://github.com/halcy/Mastodon.py/files/10788385/syslog.txt)

**Comment by ianh** [comment]
Here's the text inline in case it's more convenient to read:
```Exception in thread Thread-1 (_threadproc):
Traceback (most recent call last):
  File "/home/ianh/discord-mastodon-bridge/venv/lib/python3.11/site-packages/urllib3/response.py", line 444, in _error_catcher
    yield
  File "/home/ianh/discord-mastodon-bridge/venv/lib/python3.11/site-packages/urllib3/response.py", line 828, in read_chunked
    self._update_chunk_length()
  File "/home/ianh/discord-mastodon-bridge/venv/lib/python3.11/site-packages/urllib3/response.py", line 758, in _update_chunk_length
    line = self._fp.fp.readline()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ianh/discord-mastodon-bridge/python-root/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ianh/discord-mastodon-bridge/python-root/lib/python3.11/ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ianh/discord-mastodon-bridge/python-root/lib/python3.11/ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ianh/discord-mastodon-bridge/venv/lib/python3.11/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home/ianh/discord-mastodon-bridge/venv/lib/python3.11/site-packages/urllib3/response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/ianh/discord-mastodon-bridge/venv/lib/python3.11/site-packages/urllib3/response.py", line 816, in read_chunked
    with self._error_catcher():
  File "/home/ianh/discord-mastodon-bridge/python-root/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ianh/discord-mastodon-bridge/venv/lib/python3.11/site-packages/urllib3/response.py", line 449, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='mas.to', port=443): Read timed out.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ianh/discord-mastodon-bridge/python-root/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/ianh/discord-mastodon-bridge/python-root/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ianh/discord-mastodon-bridge/venv/lib/python3.11/site-packages/mastodon/internals.py", line 494, in _threadproc
    listener.handle_stream(r)
  File "/home/ianh/discord-mastodon-bridge/venv/lib/python3.11/site-packages/mastodon/streaming.py", line 109, in handle_stream
    for chunk in response.iter_content(chunk_size=1):
  File "/home/ianh/discord-mastodon-bridge/venv/lib/python3.11/site-packages/requests/models.py", line 822, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mas.to', port=443): Read timed out.```

**Comment by halcy** [comment]
Interesting! Thank you for the report. Will add that one (and I just noticed I broke the ReadTimeout handler, too - oops)

**Comment by halcy** [comment]
I wonder why that error can even occur there, honestly - quite weird. Oh well. Should be fixed in master, I hope. Unfortunately this is one of those things that is almost impossible to consistently test with a normal amount of effort.
