### ISSUE TITLE
 TypeError: exceptions must derive from BaseException

### ISSUE THREAD

**Issue by TomCasavant** [halcy/Mastodon.py#368]
This error popped up after the streaming api timed out 
```
Traceback (most recent call last):
File "bot.py", line 49, in <module>
     '''
   File "bot.py", line 44, in stream_timeline
     if (not status['reblogged'] and self.is_post(status)):
   File "/usr/local/lib/python3.8/site-packages/decorator.py", line 232, in fun
     return caller(func, *(extras + args), **kw)
   File "/usr/local/lib/python3.8/site-packages/mastodon/utility.py", line 49, in wrapper
     return function(self, *args, **kwargs)
   File "/usr/local/lib/python3.8/site-packages/mastodon/streaming_endpoints.py", line 21, in stream_user
     return self.__stream('/api/v1/streaming/user', listener, run_async=run_async, timeout=timeout, reconnect_async=reconnect_async, reconnect_async_wait_sec=reconnect_async_wait_sec)
   File "/usr/local/lib/python3.8/site-packages/mastodon/internals.py", line 540, in __stream
     listener.handle_stream(r)
   File "/usr/local/lib/python3.8/site-packages/mastodon/streaming.py", line 151, in handle_stream
     six.raise_from(
   File "<string>", line 3, in raise_from
 TypeError: exceptions must derive from BaseException
```

just from glancing at mastodon/streaming.py it looks like the error it's throwing *does* derive from Exception so I'm not sure what would cause this

**Comment by halcy** [comment]
That's quite weird. I can't repro it, either. Maybe some residual six weirdness. We're going to be removing that, so maybe in the newest version it will be fixed. Once that's out, maybe you can give it another shot?

**Comment by TomCasavant** [comment]
I wasn't able to consistently reproduce it at the time but I'll give it a shot with the new version

**Comment by halcy** [comment]
Should (?) be fixed in master since I think this may have been a six related issue and we don't use that anymore. Not sure how to verify that, though.
