### ISSUE TITLE
Disabling Mastodon `stream_user` version check.

### ISSUE THREAD

**Issue by GamePlayer-8** [halcy/Mastodon.py#373]
Good afternoon,

How do I disable the check of remote Mastodon instance version in Mastodon.py?

I'm using Sharkey version `v2024.3.1` which contains an API mostly compatible with Mastodon API.

The current error what I'm getting is:

```python
Traceback (most recent call last):
  File "/source/runner.py", line 218, in <module>
    setup()
  File "/source/runner.py", line 215, in setup
    main()
  File "/source/runner.py", line 194, in main
    stream = mastodon_instance.stream_user(listener, run_async=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mastodon/utility.py", line 46, in wrapper
    raise MastodonVersionError(f"Version check failed (Need version {version})")
mastodon.errors.MastodonVersionError: Version check failed (Need version 1.1.0)
```

**Comment by halcy** [comment]
Sigh. I genuinely wish people would stop making up new creative ways of formatting the version string for the API and just put the god damned version of the API that their server software tries to support in there. I already have like 3 different weird edge cases for pleroma and masto forks, apparently sharkey invented yet another way that I get to put in now ("version": "3.0.0 (compatible; Sharkey 2024.3.1)")

anyways: set "version_check_mode" to "none" (string "none", lowercase) in the constructor, that should hopefully mostly work. Some functions that disambiguate by version may not work (mostly search), use the _v1 or _v2 variants of those explicitly.

**Comment by halcy** [comment]
Ah, hm. Maybe Sharkey implements only the v2 version of the instance API, not the v1. Since Mastodon does not remove the old ones, I currently do not take that into account. I should probably do that.

Both would be good, probably, ideally they should support v1 for compat, and I should obviously use v2 when v1 is not available.

Currently once again busy with other stuff, so I can't promise a timeline on a fix, but if you want to quickly kludge it yourself, you probably can make it work by looking at api docs and swapping URLs around (maybe even just v1 to v2 in there is good enough, not sure)

**Comment by halcy** [comment]
it's per endpoint, there's (intended to be a) _v1 and _v2 version, but I think in the current stable version on pip, I didn't implement that for the v2 instance API yet. I will, eventually, but I keep getting sidetracked. As a workaround, you could edit your local copy of Mastodon.py and replace /v1/ with /v2/ in the  "__instance" function or, as you said, proxy rewrite it.

**Comment by halcy** [comment]
changed the streaming URL retriever to also work when there is only a v2 endpoint, and defaulted version checking to off.
