### ISSUE TITLE
TypeError: Mastodon.status_post() got multiple values for argument 'self'

### ISSUE THREAD

**Issue by Konano** [halcy/Mastodon.py#388]
#### Environment Information:
- **Python Version:** 3.10.9
- **Mastodon.py Version:** 1.8.1

#### Error Log:
```
Traceback (most recent call last):
  File "/home/ubuntu/bots/Project/base/debug.py", line 51, in wrap_async
    ret = await func(*args, **kwargs)
  File "/home/ubuntu/bots/Project/command/mastodon/aaaaaaaaaa.py", line 232, in tc_reply
    mastodon.status_reply(to_status=to_status, status=post.text)
  File "<decorator-gen-57>", line 2, in status_reply
  File "/home/ubuntu/.miniconda3/envs/Project/lib/python3.10/site-packages/mastodon/utility.py", line 49, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ubuntu/.miniconda3/envs/Project/lib/python3.10/site-packages/mastodon/statuses.py", line 362, in status_reply
    return self.status_post(**keyword_args)
TypeError: Mastodon.status_post() got multiple values for argument 'self'
```

**Comment by halcy** [comment]
Oops, that's a good catch. Thank you.
