### ISSUE TITLE
Exception on fetch_remaining call

### ISSUE THREAD

**Issue by mcrosson** [halcy/Mastodon.py#59]
I'm getting a very odd error when using the fetch remaining method. fetch_next works fine if I pass a previous page but the moment I try to do a call to fetch_remaining nothing seems to work.

Have you seen this behavior before?

Sample code
        first_page = mastodon.timeline_local(since_id=last_seen_toot_id)
        remaining_pages = mastodon.fetch_remaining(first_page)

Stack Trace

Traceback (most recent call last):
  File ".\toot_bot.py", line 224, in <module>
    welcome(CONFIG)
  File ".\toot_bot.py", line 144, in welcome
    mastodon.public_stream(WelcomeBot(config))
  File "C:\Users\mcros\src\mastodon_bot\BotStreamListeners.py", line 37, in __init__
    self.replay_toots(True)
  File "C:\Users\mcros\src\mastodon_bot\BotStreamListeners.py", line 55, in replay_toots
    remaining_pages = mastodon.fetch_remaining(first_page)
  File "C:\Program Files\Python36\lib\site-packages\mastodon\Mastodon.py", line 814, in fetch_remaining
    current_page = self.fetch_next(current_page)
  File "C:\Program Files\Python36\lib\site-packages\mastodon\Mastodon.py", line 760, in fetch_next
    if '_pagination_next' in previous_page[-1]:
IndexError: list index out of range

**Comment by mcrosson** [comment]
Poking at it further and I discovered line 812 (https://github.com/halcy/Mastodon.py/blob/master/mastodon/Mastodon.py#L812) needs "and len(current_page) > 0" added to the conditional of the while statement.

An empty list is returned at the end of the fetch_next cycle and it's causing an exception in fetch_remaining.

**Comment by mcrosson** [comment]
Quick update, the conditional should probably use "and not current_page" instead of my previous code sample.

My apologies for the newbie mistake.

**Comment by halcy** [comment]
The first one is probably clearer, so I'll go with that.
