### ISSUE TITLE
Don't raise on invalid link headers

### ISSUE THREAD

**Issue by codl** [halcy/Mastodon.py#75]
In some circumstances it seems mastodon will respond with an empty link header. This shouldn't raise an exception

```
Mastodon: Request to endpoint "/api/v1/accounts/1/statuses" using method "GET".
Parameters: {'limit': 40, 'since_id': '6', 'max_id': 7}
Headers: {'Authorization': 'Bearer aaabbbcccdddeeefff'}
Files: {}
Mastodon: Response received with code 200.
response headers: {'X-Frame-Options': 'SAMEORIGIN', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Type': 'application/json; charset=utf-8', 'Link': '', 'Vary': 'Accept-Encoding, Origin', 'Content-Encoding': 'gzip', 'ETag': 'W/"0e4553e4ec97dd1f5d499c85b7dcc538"', 'Cache-Control': 'max-age=0, private, must-revalidate', 'X-Request-Id': 'd87dcb95-eaf9-48e9-97f6-3ffd385c01ae', 'X-Runtime': '0.020305', 'Transfer-Encoding': 'chunked'}
Response text content: []

Traceback (most recent call last):
  File "/home/codl/dev/forget/venv/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "tasks.py", line 39, in __call__
    super().__call__(*args, **kwargs)
  File "/home/codl/dev/forget/venv/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/codl/dev/forget/venv/lib/python3.6/site-packages/celery/app/base.py", line 472, in run
    return task._orig_run(*args, **kwargs)
  File "tasks.py", line 55, in fetch_acc
    cursor = action(acc, cursor)
  File "/home/codl/dev/forget/lib/mastodon.py", line 105, in fetch_acc
    statuses = api.account_statuses(acc.mastodon_id, **kwargs)
  File "/home/codl/dev/forget/venv/lib/python3.6/site-packages/mastodon/Mastodon.py", line 364, in account_statuses
    return self.__api_request('GET', '/api/v1/accounts/' + str(id) + '/statuses', params)
  File "/home/codl/dev/forget/venv/lib/python3.6/site-packages/mastodon/Mastodon.py", line 963, in __api_request
    if url['rel'] == 'next':
KeyError: 'rel'
```

**Comment by codl** [comment]
My bad, I did not realise this was already fixed in master. Closing...
