### ISSUE TITLE
Issue with pagination: IndexError: list index out of range

### ISSUE THREAD

**Issue by chaica** [halcy/Mastodon.py#81]
Hi,

While using pagination, it crashes when my account followers number is 320. It does not happen on other accounts with a different account followers number:
```
$ ./mastocount.py -c coins.ini 
Traceback (most recent call last):
  File "./mastocount.py", line 35, in <module>
    Main()
  File "/home/chaica/progra/python/mastocount/mastocount/main.py", line 36, in __init__
    self.main()
  File "/home/chaica/progra/python/mastocount/mastocount/main.py", line 44, in main
    followers = get_followers(credential)
  File "/home/chaica/progra/python/mastocount/mastocount/followers.py", line 38, in get_followers
    for page in mastodon.fetch_remaining(res):
  File "/usr/local/lib/python3.5/dist-packages/mastodon/Mastodon.py", line 814, in fetch_remaining
    current_page = self.fetch_next(current_page)
  File "/usr/local/lib/python3.5/dist-packages/mastodon/Mastodon.py", line 760, in fetch_next
    if '_pagination_next' in previous_page[-1]:
IndexError: list index out of range
```
It does not happen with the same account if the number is not 320, e.g 319.

Cheers,
Carl

**Comment by halcy** [comment]
Should be fixed by 1c93e350f74626b67bb50503d6ee6fcb9656bc2b

**Comment by halcy** [comment]
That is to say: If you were using the newest version from master at that time, please do reopen this, but I think I fixed that.

**Comment by chaica** [comment]
No it does not, I already have applied 1c93e35 on my Mastodon.py

**Comment by halcy** [comment]
Bother. Guess I'll hold off doing a release until that's not broken anymore.

**Comment by halcy** [comment]
Actually, fixed, probably - can you try with the newest version from master now?

**Comment by chaica** [comment]
It works great with the latest version from master. Thanks a lot!
